# Simple workflow for building the documentation on branches as a test
name: Build documentation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - name: versions
        run: ./src/scripts/versions.sh
      - name: install
        run: npm install
      - name: build
        run: npx docusaurus build
      - name: Archive build/
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
